function renderAdmin(){
  if(!state.session)return shell(`<main class="page">${authGate('Admin memerlukan akun yang terdaftar sebagai admin member.')}</main>`,'profile');
  if(!state.isAdmin)return shell(`<main class="page"><div class="empty"><div class="empty-icon">⌁</div><h3>Akun ini bukan admin.</h3><p>Tambahkan user ID ini ke tabel <b>admin_members</b> melalui Supabase Dashboard untuk membuka CMS: ${esc(state.session.user.id)}</p><button class="btn btn-white" data-go="profile">Kembali ke profil</button></div></main>`,'profile');
  const tab=state.adminTab;
  const tabButtons=['topics','videos','health'].map(x=>`<button class="admin-tab ${tab===x?'active':''}" data-admin-tab="${x}">${x==='topics'?'Topik':x==='videos'?'Video':'Content health'}</button>`).join('');
  let body='';
  if(tab==='topics'){
    body=`<div class="admin-grid"><div class="admin-list">${state.topics.map(t=>`<div class="admin-row"><div><h4>${esc(t.title)}</h4><p>${esc(stageById(t.stage_id)?.short_label||'')} · ${esc(domainById(t.domain_id)?.name||'')} · ${t.published?'Published':'Draft'}</p></div><div class="admin-row-actions"><button class="btn btn-white btn-sm" data-admin-edit-topic="${esc(t.id)}">Edit</button><button class="btn ${t.published?'btn-danger':'btn-soft'} btn-sm" data-admin-toggle-topic="${esc(t.id)}">${t.published?'Unpublish':'Publish'}</button></div></div>`).join('')}</div>
    <form id="topic-form" class="admin-form"><h3 id="topic-form-title">Tambah topik</h3><input type="hidden" name="id"/><div class="field"><label>Judul</label><input name="title" required/></div><div class="mini-grid"><div class="field"><label>Fase</label><select name="stage_id" required>${state.stages.map(s=>`<option value="${esc(s.id)}">${esc(s.short_label)}</option>`).join('')}</select></div><div class="field"><label>Area</label><select name="domain_id" required>${state.domains.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('')}</select></div></div><div class="field"><label>Deskripsi singkat</label><textarea name="short_description" required></textarea></div><div class="field"><label>Why now</label><textarea name="why_now" required></textarea></div><div class="field"><label>Action prompt</label><textarea name="action_prompt" required></textarea></div><div class="field"><label>Reflection prompt</label><textarea name="reflection_prompt" required></textarea></div><div class="mini-grid"><div class="field"><label>Urutan</label><input name="sort_order" type="number" value="40"/></div><div class="field"><label>Status</label><select name="published"><option value="true">Published</option><option value="false">Draft</option></select></div></div><button class="btn btn-primary" type="submit">Simpan topik</button></form></div>`
  }else if(tab==='videos'){
    body=`<div class="admin-grid"><div class="admin-list">${state.videos.map(v=>`<div class="admin-row"><div><h4>${esc(v.title)}</h4><p>${esc(v.channel)} · score ${esc(v.curator_score??'-')} · ${esc(v.credibility_level)}</p></div><div class="admin-row-actions"><a class="btn btn-white btn-sm" href="https://youtube.com/watch?v=${esc(v.youtube_id)}" target="_blank" rel="noopener">Buka ↗</a></div></div>`).join('')}</div>
    <div><form id="video-form" class="admin-form"><h3>Tambah video YouTube</h3><div class="field"><label>YouTube ID</label><input name="youtube_id" placeholder="contoh: eIho2S0ZahI" required/></div><div class="field"><label>Judul</label><input name="title" required/></div><div class="field"><label>Channel</label><input name="channel" required/></div><div class="field"><label>Kenapa dipilih</label><textarea name="why_selected" required></textarea></div><div class="mini-grid"><div class="field"><label>Curator score</label><input name="curator_score" type="number" min="0" max="100" value="80"/></div><div class="field"><label>Kredibilitas</label><select name="credibility_level"><option value="reviewed">Reviewed</option><option value="expert_reviewed">Expert reviewed</option><option value="official_source">Official source</option></select></div></div><button class="btn btn-primary" type="submit">Tambah video</button></form>
    <form id="link-form" class="admin-form" style="margin-top:12px"><h3>Hubungkan ke topik</h3><div class="field"><label>Topik</label><select name="topic_id">${state.topics.map(t=>`<option value="${esc(t.id)}">${esc(t.title)}</option>`).join('')}</select></div><div class="field"><label>Video</label><select name="video_id">${state.videos.map(v=>`<option value="${esc(v.id)}">${esc(v.title)}</option>`).join('')}</select></div><div class="field"><label>Peran</label><select name="role"><option value="start_here">Start here</option><option value="go_deeper">Go deeper</option><option value="real_story">Real story</option></select></div><button class="btn btn-dark" type="submit">Hubungkan</button></form></div></div>`
  }else{
    const rows=state.topics.map(t=>{const links=state.topicVideos.filter(x=>x.topic_id===t.id);return `<div class="health-row"><div><h4>${esc(t.title)}</h4><small>${esc(stageById(t.stage_id)?.short_label||'')} · ${esc(domainById(t.domain_id)?.name||'')}</small></div><span class="chip ${links.length?'chip-green':''}">${links.length?'Ada video':'Belum ada video'}</span><span class="chip">${t.published?'Published':'Draft'}</span></div>`}).join('');
    body=`<div class="admin-panel"><div class="section-head"><div><h2>Content health</h2><p>Ringkasan sederhana untuk melihat topik yang masih membutuhkan materi kurasi.</p></div></div>${rows}</div>`
  }
  return shell(`<main class="page"><div class="admin-head"><div><span class="eyebrow">CMS · curator workspace</span><h1>Kelola roadmap tanpa mengubah kode.</h1></div><button class="btn btn-white" data-go="home">Lihat situs</button></div><div class="admin-tabs">${tabButtons}</div>${body}</main>`,'profile')
}
function openAuth(){
  modalRoot.innerHTML=`<div class="modal-backdrop" data-close-modal><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><div><span class="eyebrow">Akun MauKeMana</span><h2>Simpan perjalananmu.</h2></div><button class="modal-close" data-close-modal>×</button></div><form id="auth-form"><div class="field"><label>Email</label><input type="email" name="email" placeholder="nama@email.com" required/></div><button class="btn btn-primary btn-block" style="margin-top:12px" type="submit">Kirim magic link</button><p class="modal-note">Tidak ada password. Kami kirim tautan masuk ke emailmu. Akun digunakan untuk Saved, progress, refleksi, dan preferensi.</p></form></div></div>`;bindModal()
}
function openOnboarding(){
  const group=state.selectedStage.startsWith('sma')?'sma':'s1';
  modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><span class="eyebrow">Atur konteksmu</span><h2>Kamu sedang ada di fase mana?</h2></div>${localStorage.getItem('mk_onboarded')?`<button class="modal-close" data-close-modal>×</button>`:''}</div><div class="onboard-options" style="margin-bottom:12px"><button class="onboard-option ${group==='sma'?'active':''}" data-onboard-group="sma"><strong>SMA</strong><span>Kelas 10–12</span></button><button class="onboard-option ${group==='s1'?'active':''}" data-onboard-group="s1"><strong>Kuliah S1</strong><span>Semester 1–8</span></button></div><div id="stage-options" class="onboard-options">${onboardStageOptions(group)}</div><h3 style="font-size:13px;margin:22px 0 10px">Minat tambahan <span class="muted" style="font-weight:500">· opsional</span></h3><div class="interest-picks">${state.interests.map(i=>`<button class="pick ${state.selectedInterests.has(i.id)?'active':''}" data-onboard-interest="${esc(i.id)}">${esc(i.label)}</button>`).join('')}</div><button class="btn btn-primary btn-block" style="margin-top:22px" data-action="finish-onboarding">Gunakan roadmap ini</button><p class="modal-note">Kamu tetap bisa membuka semua topik. Pilihan ini hanya menentukan urutan dan konteks utama.</p></div></div>`;bindModal()
}
function onboardStageOptions(group){return state.stages.filter(s=>s.kind===group).map(s=>`<button class="onboard-option ${s.id===state.selectedStage?'active':''}" data-onboard-stage="${esc(s.id)}"><strong>${esc(s.short_label)}</strong><span>${esc(s.phase)}</span></button>`).join('')}
function closeModal(){modalRoot.innerHTML=''}
function bindModal(){
  modalRoot.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));
  const form=modalRoot.querySelector('#auth-form');if(form)form.addEventListener('submit',sendMagicLink);
  modalRoot.querySelectorAll('[data-onboard-group]').forEach(b=>b.addEventListener('click',()=>{const group=b.dataset.onboardGroup;modalRoot.querySelectorAll('[data-onboard-group]').forEach(x=>x.classList.toggle('active',x===b));modalRoot.querySelector('#stage-options').innerHTML=onboardStageOptions(group);bindModal()}));
  modalRoot.querySelectorAll('[data-onboard-stage]').forEach(b=>b.addEventListener('click',()=>{state.selectedStage=b.dataset.onboardStage;modalRoot.querySelectorAll('[data-onboard-stage]').forEach(x=>x.classList.toggle('active',x.dataset.onboardStage===state.selectedStage))}));
  modalRoot.querySelectorAll('[data-onboard-interest]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.onboardInterest;state.selectedInterests.has(id)?state.selectedInterests.delete(id):state.selectedInterests.add(id);b.classList.toggle('active',state.selectedInterests.has(id))}));
  const finish=modalRoot.querySelector('[data-action="finish-onboarding"]');if(finish)finish.addEventListener('click',finishOnboarding)
}
async function sendMagicLink(e){e.preventDefault();const email=new FormData(e.currentTarget).get('email');const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname+'#home'}});if(error)return toast(error.message,'error');e.currentTarget.innerHTML=`<div class="auth-success">Magic link sudah dikirim. Cek inbox email ${esc(email)}.</div>`}
async function finishOnboarding(){localStorage.setItem('mk_stage',state.selectedStage);localStorage.setItem('mk_interests',JSON.stringify([...state.selectedInterests]));localStorage.setItem('mk_onboarded','1');if(state.session){state.userInterests=new Set(state.selectedInterests);await saveProfile()}closeModal();render();toast('Roadmap disesuaikan dengan fase kamu')}
async function requireAuth(){if(state.session)return true;openAuth();return false}
async function toggleSave(id){if(!await requireAuth())return;const uid=state.session.user.id;if(state.saves.has(id)){const {error}=await db.from('saved_topics').delete().eq('user_id',uid).eq('topic_id',id);if(error)return toast(error.message,'error');state.saves.delete(id);toast('Dihapus dari Saved')}else{const {error}=await db.from('saved_topics').insert({user_id:uid,topic_id:id});if(error)return toast(error.message,'error');state.saves.add(id);toast('Disimpan ke Saved')}render()}
async function setProgress(id,status){if(!await requireAuth())return;const uid=state.session.user.id;const {error}=await db.from('topic_progress').upsert({user_id:uid,topic_id:id,status,updated_at:new Date().toISOString()},{onConflict:'user_id,topic_id'});if(error)return toast(error.message,'error');state.progress[id]=status;render();toast(status==='tried'?'Bagus. Yang penting sudah dicoba.':'Progress diperbarui')}
async function saveReflection(id){if(!await requireAuth())return;const input=document.querySelector('#reflection-input');const body=input?.value.trim();if(!body)return toast('Tulis refleksimu dulu','error');const uid=state.session.user.id;const existing=await db.from('reflections').select('id').eq('user_id',uid).eq('topic_id',id).order('created_at',{ascending:false}).limit(1).maybeSingle();let res;if(existing.data?.id)res=await db.from('reflections').update({body}).eq('id',existing.data.id);else res=await db.from('reflections').insert({user_id:uid,topic_id:id,body});if(res.error)return toast(res.error.message,'error');state.reflections[id]=body;toast('Refleksi tersimpan');render()}
async function sendFeedback(id,rating){if(!await requireAuth())return;const {error}=await db.from('content_feedback').insert({user_id:state.session.user.id,topic_id:id,rating});if(error)return toast(error.message,'error');toast('Terima kasih. Ini masuk ke review kurasi.')}
async function saveProfile(){if(!state.session)return;const stage=document.querySelector('#profile-stage')?.value||state.selectedStage;const uid=state.session.user.id;const picks=[...state.userInterests];const {error}=await db.from('profiles').upsert({id:uid,life_stage_id:stage,display_name:state.profile?.display_name||state.session.user.email.split('@')[0],updated_at:new Date().toISOString()},{onConflict:'id'});if(error)return toast(error.message,'error');await db.from('user_interests').delete().eq('user_id',uid);if(picks.length){const ins=await db.from('user_interests').insert(picks.map(interest_id=>({user_id:uid,interest_id})));if(ins.error)return toast(ins.error.message,'error')}state.selectedStage=stage;localStorage.setItem('mk_stage',stage);await loadUser();render();toast('Preferensi disimpan')}
async function adminSaveTopic(form){const f=Object.fromEntries(new FormData(form));const payload={id:f.id||slugify(`${f.stage_id}-${f.title}`),title:f.title,stage_id:f.stage_id,domain_id:f.domain_id,short_description:f.short_description,why_now:f.why_now,action_prompt:f.action_prompt,reflection_prompt:f.reflection_prompt,sort_order:Number(f.sort_order)||40,published:f.published==='true',updated_at:new Date().toISOString()};const {error}=await db.from('topics').upsert(payload,{onConflict:'id'});if(error)return toast(error.message,'error');await loadCatalog();render();toast('Topik tersimpan')}
async function adminSaveVideo(form){const f=Object.fromEntries(new FormData(form));const {error}=await db.from('videos').insert({youtube_id:f.youtube_id,title:f.title,channel:f.channel,why_selected:f.why_selected,curator_score:Number(f.curator_score)||null,credibility_level:f.credibility_level,reviewed_at:new Date().toISOString().slice(0,10),published:true});if(error)return toast(error.message,'error');await loadCatalog();render();toast('Video masuk katalog')}
async function adminLinkVideo(form){const f=Object.fromEntries(new FormData(form));const {error}=await db.from('topic_videos').upsert({topic_id:f.topic_id,video_id:f.video_id,role:f.role,sort_order:10},{onConflict:'topic_id,video_id'});if(error)return toast(error.message,'error');await loadCatalog();render();toast('Video terhubung ke topik')}
async function adminToggleTopic(id){const t=topicById(id);if(!t)return;const {error}=await db.from('topics').update({published:!t.published,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message,'error');await loadCatalog();render();toast(t.published?'Topik dijadikan draft':'Topik dipublikasikan')}
function adminEditTopic(id){const t=topicById(id),form=document.querySelector('#topic-form');if(!t||!form)return;for(const [k,v] of Object.entries(t)){if(form.elements[k])form.elements[k].value=String(v)}document.querySelector('#topic-form-title').textContent='Edit topik';form.scrollIntoView({behavior:'smooth',block:'start'})}
function slugify(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)}
function bind(){
  document.querySelectorAll('[data-go]').forEach(x=>x.addEventListener('click',()=>go(x.dataset.go)));
  document.querySelectorAll('[data-action="auth"]').forEach(x=>x.addEventListener('click',openAuth));
  document.querySelectorAll('[data-action="onboarding"]').forEach(x=>x.addEventListener('click',openOnboarding));
  document.querySelectorAll('[data-action="signout"]').forEach(x=>x.addEventListener('click',async()=>{await db.auth.signOut();toast('Kamu sudah keluar')}));
  document.querySelectorAll('[data-stage]').forEach(x=>x.addEventListener('click',()=>{state.selectedStage=x.dataset.stage;localStorage.setItem('mk_stage',state.selectedStage);render()}));
  document.querySelectorAll('[data-domain]').forEach(x=>x.addEventListener('click',()=>{state.exploreDomain=x.dataset.domain;state.exploreStage='all';go('explore')}));
  document.querySelectorAll('[data-save]').forEach(x=>x.addEventListener('click',()=>toggleSave(x.dataset.save)));
  document.querySelectorAll('[data-progress]').forEach(x=>x.addEventListener('click',()=>setProgress(x.dataset.topic,x.dataset.progress)));
  document.querySelectorAll('[data-reflection]').forEach(x=>x.addEventListener('click',()=>saveReflection(x.dataset.reflection)));
  document.querySelectorAll('[data-feedback]').forEach(x=>x.addEventListener('click',()=>sendFeedback(x.dataset.topic,Number(x.dataset.feedback))));
  const q=document.querySelector('#explore-search');if(q)q.addEventListener('input',e=>{state.exploreQuery=e.target.value;clearTimeout(window.__searchTimer);window.__searchTimer=setTimeout(render,180)});
  const df=document.querySelector('#domain-filter');if(df)df.addEventListener('change',e=>{state.exploreDomain=e.target.value;render()});const sf=document.querySelector('#stage-filter');if(sf)sf.addEventListener('change',e=>{state.exploreStage=e.target.value;render()});
  document.querySelectorAll('[data-interest]').forEach(x=>x.addEventListener('click',()=>{const id=x.dataset.interest;state.userInterests.has(id)?state.userInterests.delete(id):state.userInterests.add(id);x.classList.toggle('active',state.userInterests.has(id))}));
  const sp=document.querySelector('[data-action="save-profile"]');if(sp)sp.addEventListener('click',saveProfile);
  document.querySelectorAll('[data-admin-tab]').forEach(x=>x.addEventListener('click',()=>{state.adminTab=x.dataset.adminTab;render()}));
  document.querySelectorAll('[data-admin-toggle-topic]').forEach(x=>x.addEventListener('click',()=>adminToggleTopic(x.dataset.adminToggleTopic)));
  document.querySelectorAll('[data-admin-edit-topic]').forEach(x=>x.addEventListener('click',()=>adminEditTopic(x.dataset.adminEditTopic)));
  const tf=document.querySelector('#topic-form');if(tf)tf.addEventListener('submit',e=>{e.preventDefault();adminSaveTopic(tf)});
  const vf=document.querySelector('#video-form');if(vf)vf.addEventListener('submit',e=>{e.preventDefault();adminSaveVideo(vf)});
  const lf=document.querySelector('#link-form');if(lf)lf.addEventListener('submit',e=>{e.preventDefault();adminLinkVideo(lf)});
}
function render(){
  if(state.loading){app.innerHTML=`<div class="boot-screen"><div class="boot-mark">MK</div><p>Menyiapkan arahmu…</p></div>`;return}
  const r=route();let html;
  if(r==='home')html=renderHome();else if(r==='roadmap')html=renderRoadmap();else if(r==='explore')html=renderExplore();else if(r==='saved')html=renderSaved();else if(r==='profile')html=renderProfile();else if(r==='admin')html=renderAdmin();else if(r.startsWith('topic/'))html=renderTopic(decodeURIComponent(r.split('/').slice(1).join('/')));else html=renderHome();
  app.innerHTML=html;bind()
}
window.addEventListener('hashchange',render);init();