function renderRoadmap(){
  const all=state.stages.map((s,si)=>{
    const topics=state.topics.filter(t=>t.stage_id===s.id).sort((a,b)=>a.sort_order-b.sort_order);const done=topics.filter(t=>state.progress[t.id]==='tried').length;
    return `<section class="roadmap-stage"><div class="roadmap-stage-head"><div class="roadmap-stage-num">${String(si+1).padStart(2,'0')}</div><div><h3>${esc(s.label)} · ${esc(s.phase)}</h3><p>${esc(s.tagline)}</p></div><div class="stage-progress">${done}/${topics.length} dicoba</div></div>
    ${topics.map((t,i)=>`<a href="#topic/${encodeURIComponent(t.id)}" class="roadmap-topic-row"><span class="roadmap-topic-index">${String(i+1).padStart(2,'0')}</span><div><h4>${esc(t.title)}</h4><p>${esc(domainById(t.domain_id)?.name||'')}</p></div><span class="progress-tag ${progressClass(state.progress[t.id])}">${esc(progressLabel(state.progress[t.id]))}</span><span>→</span></a>`).join('')}</section>`
  }).join('');
  const done=Object.values(state.progress).filter(x=>x==='tried').length;
  const content=`<main class="page"><section class="roadmap-hero"><div><span class="eyebrow">Roadmap pengembangan diri</span><h1>Dari fase hidup, bukan dari algoritma.</h1><p>Setiap fase punya pertanyaan yang berbeda. Roadmap ini membantu kamu memusatkan perhatian pada hal yang paling masuk akal untuk dipelajari sekarang.</p></div><div class="roadmap-stat"><div class="statbox"><b>${state.stages.length}</b><small>fase</small></div><div class="statbox"><b>${state.topics.length}</b><small>topik</small></div><div class="statbox"><b>${done}</b><small>dicoba</small></div></div></section>
  <div class="stage-strip section">${state.stages.map(s=>`<button class="stage-btn ${s.id===state.selectedStage?'active':''}" data-stage="${esc(s.id)}"><strong>${esc(s.short_label)}</strong><span>${esc(s.phase)}</span></button>`).join('')}</div><div class="roadmap-list">${all}</div></main>`;
  return shell(content,'roadmap')
}
function renderExplore(){
  let topics=[...state.topics];const q=state.exploreQuery.trim().toLowerCase();
  if(q)topics=topics.filter(t=>`${t.title} ${t.short_description} ${domainById(t.domain_id)?.name||''}`.toLowerCase().includes(q));
  if(state.exploreDomain!=='all')topics=topics.filter(t=>t.domain_id===state.exploreDomain);
  if(state.exploreStage==='current')topics=topics.filter(t=>t.stage_id===state.selectedStage);else if(state.exploreStage!=='all')topics=topics.filter(t=>t.stage_id===state.exploreStage);
  const content=`<main class="page"><div class="section-head"><div><span class="eyebrow">Explore</span><h2>Jelajahi tanpa tersesat.</h2><p>Cari topik spesifik. Tidak ada infinite feed; kamu selalu tahu konteks setiap materi.</p></div></div>
  <div class="filterbar"><div class="searchbox"><input id="explore-search" placeholder="Cari topik, misalnya fokus, uang, komunikasi…" value="${esc(state.exploreQuery)}" /></div><select id="domain-filter" class="select"><option value="all">Semua area</option>${state.domains.map(d=>`<option value="${esc(d.id)}" ${state.exploreDomain===d.id?'selected':''}>${esc(d.name)}</option>`).join('')}</select><select id="stage-filter" class="select"><option value="current" ${state.exploreStage==='current'?'selected':''}>Fase saya</option><option value="all" ${state.exploreStage==='all'?'selected':''}>Semua fase</option>${state.stages.map(s=>`<option value="${esc(s.id)}" ${state.exploreStage===s.id?'selected':''}>${esc(s.short_label)}</option>`).join('')}</select></div>
  <section class="section"><div class="section-head"><div><h2>${topics.length} topik ditemukan</h2></div></div>${topics.length?`<div class="grid grid-3">${topics.map(topicCard).join('')}</div>`:`<div class="empty"><div class="empty-icon">⌕</div><h3>Belum ada yang cocok.</h3><p>Coba kata kunci atau filter yang lebih luas.</p></div>`}</section></main>`;
  return shell(content,'explore')
}
function renderSaved(){
  const topics=state.topics.filter(t=>state.saves.has(t.id));
  const content=`<main class="page"><div class="section-head"><div><span class="eyebrow">Saved</span><h2>Simpan yang ingin kamu kembali lagi.</h2><p>Bookmark bukan antrean tanpa akhir. Gunakan hanya untuk materi yang benar-benar ingin kamu lanjutkan.</p></div></div>${!state.session?authGate('Masuk untuk menyimpan topik dan melanjutkan progresmu di perangkat lain.'):(topics.length?`<div class="grid grid-3">${topics.map(topicCard).join('')}</div>`:`<div class="empty"><div class="empty-icon">♡</div><h3>Belum ada topik tersimpan.</h3><p>Ketika menemukan topik penting, tekan Simpan di halaman topik.</p><button class="btn btn-primary" data-go="explore">Mulai eksplorasi</button></div>`)}</main>`;
  return shell(content,'saved')
}
function authGate(text){return `<div class="empty"><div class="empty-icon">↗</div><h3>Progres ini milikmu.</h3><p>${esc(text)}</p><button class="btn btn-primary" data-action="auth">Masuk / buat akun</button></div>`}
function renderProfile(){
  if(!state.session)return shell(`<main class="page"><div class="section-head"><div><span class="eyebrow">Profil</span><h2>Satu akun untuk menyimpan perjalananmu.</h2></div></div>${authGate('Akun hanya diperlukan ketika kamu ingin menyimpan progres, refleksi, dan preferensi.')}</main>`,'profile');
  const tried=Object.values(state.progress).filter(x=>x==='tried').length,watched=Object.values(state.progress).filter(x=>x==='watched').length;const picks=state.userInterests.size?state.userInterests:state.selectedInterests;
  const content=`<main class="page"><div class="section-head"><div><span class="eyebrow">Profil</span><h2>Atur konteks, bukan persona.</h2><p>Semakin jelas fase dan minatmu, semakin relevan jalur yang ditampilkan.</p></div>${state.isAdmin?`<button class="btn btn-dark" data-go="admin">Buka Admin</button>`:''}</div>
  <div class="profile-grid"><section class="card profile-card"><div class="profile-avatar">${esc(initials())}</div><h2>${esc(state.profile?.display_name||'Pengguna MauKeMana')}</h2><p>${esc(state.session.user.email)}</p><div class="profile-stats"><div class="profile-stat"><b>${state.saves.size}</b><small>saved</small></div><div class="profile-stat"><b>${watched}</b><small>watched</small></div><div class="profile-stat"><b>${tried}</b><small>tried</small></div></div><button class="btn btn-white btn-block" style="margin-top:18px" data-action="signout">Keluar</button></section>
  <section class="card settings-card"><h3>Fase hidup</h3><div class="field"><select id="profile-stage">${state.stages.map(s=>`<option value="${esc(s.id)}" ${state.selectedStage===s.id?'selected':''}>${esc(s.label)} — ${esc(s.phase)}</option>`).join('')}</select><div class="field-help">Fase menentukan urutan roadmap utama, bukan membatasi topik yang bisa kamu eksplorasi.</div></div><h3 style="margin-top:28px">Minat tambahan</h3><div class="interest-picks">${state.interests.map(i=>`<button class="pick ${picks.has(i.id)?'active':''}" data-interest="${esc(i.id)}">${esc(i.label)}</button>`).join('')}</div><div style="margin-top:22px"><button class="btn btn-primary" data-action="save-profile">Simpan preferensi</button></div></section></div></main>`;
  return shell(content,'profile')
}
function renderTopic(id){
  const t=topicById(id);if(!t)return shell(`<main class="page">${authGate('Topik tidak ditemukan atau belum dipublikasikan.')}</main>`,'explore');
  const d=domainById(t.domain_id),s=stageById(t.stage_id),links=state.topicVideos.filter(x=>x.topic_id===t.id),videos=links.map(x=>({link:x,video:videoById(x.video_id)})).filter(x=>x.video);
  const p=state.progress[t.id]||'exploring',saved=state.saves.has(t.id),reflection=state.reflections[t.id]||'';
  const content=`<main class="page topic-page"><a class="topic-back" href="#roadmap">← Kembali ke roadmap</a><section class="topic-hero"><div><div class="topic-meta"><span class="chip chip-blue">${esc(d?.name||'Topik')}</span><span class="chip">${esc(s?.short_label||'')}</span></div><h1>${esc(t.title)}</h1><p class="topic-lead">${esc(t.short_description)}</p></div><aside class="topic-side"><div><small>STATUS PERJALANAN</small><h3>${esc(progressLabel(p))}</h3></div><div><button class="btn btn-white" data-progress="watched" data-topic="${esc(t.id)}">Tandai ditonton</button><button class="btn btn-soft" data-progress="tried" data-topic="${esc(t.id)}">Tandai sudah dicoba</button><button class="btn ${saved?'btn-danger':'btn-white'}" data-save="${esc(t.id)}">${saved?'Hapus dari Saved':'Simpan topik'}</button></div></aside></section>
  <section class="topic-block why-card"><span class="eyebrow">Kenapa sekarang</span><h2>Relevansi untuk fase ini.</h2><p>${esc(t.why_now)}</p></section>
  <section class="topic-block"><span class="eyebrow">Kurasi manusia</span><h2>Video yang dipilih, bukan feed yang dipersonalisasi.</h2><p>Setiap video ditambahkan melalui proses kurasi dan diberi alasan pemilihan. Tidak ada autoplay.</p>${videos.length?`<div class="video-grid">${videos.map(({link,video})=>`<article class="video-card"><div class="video-frame"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/${esc(video.youtube_id)}" title="${esc(video.title)}" allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><div class="video-body"><span class="video-role">${esc(link.role.replace('_',' '))}</span><h3>${esc(video.title)}</h3><span class="chip">${esc(video.channel)} · ${esc(formatDuration(video.duration_seconds))}</span><p>${esc(video.why_selected)}</p></div></article>`).join('')}</div>`:`<div class="empty" style="margin-top:18px"><div class="empty-icon">▶</div><h3>Video untuk topik ini masih dikurasi.</h3><p>Roadmap tetap bisa dipakai melalui konteks, refleksi, dan aksi. Admin dapat menambahkan video setelah lolos review.</p></div>`}</section>
  <section class="topic-block"><div class="action-card"><span class="eyebrow" style="color:#cdd9ff">Aksi kecil</span><h3>Jangan berhenti di “paham”.</h3><p>${esc(t.action_prompt)}</p><button class="btn btn-white" data-progress="tried" data-topic="${esc(t.id)}">Saya akan mencobanya</button></div></section>
  <section class="topic-block"><span class="eyebrow">Refleksi</span><h2>${esc(t.reflection_prompt)}</h2><div class="reflection-box"><textarea id="reflection-input" class="select" style="width:100%;min-height:130px;resize:vertical" placeholder="Tulis untuk dirimu sendiri…">${esc(reflection)}</textarea><div><button class="btn btn-primary" data-reflection="${esc(t.id)}">Simpan refleksi</button> ${reflection?`<span class="reflection-saved">Tersimpan di akunmu</span>`:''}</div></div></section>
  <section class="topic-block"><span class="eyebrow">Bantu kurasi</span><h2>Apakah topik ini membantu?</h2><div class="feedback-row"><button class="feedback-btn" data-feedback="3" data-topic="${esc(t.id)}">Membantu</button><button class="feedback-btn" data-feedback="2" data-topic="${esc(t.id)}">Lumayan</button><button class="feedback-btn" data-feedback="1" data-topic="${esc(t.id)}">Perlu diperbaiki</button></div></section></main>`;
  return shell(content,'roadmap')
}